[package]
name = "postmark-tti"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
hdrhistogram = "7.5.4"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
walkdir = "2.5.0"
