[package]
name = "postmark-tti-histogram"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.95"
hdrhistogram = "7.5.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
walkdir = "2.5.0"
